### ISSUE TITLE
JsonImporter does not clear existing bend points

### ISSUE THREAD

**Issue by spoenemann** [eclipse/elk#1001]
Looking more closely at issue https://github.com/eclipse-sprotty/sprotty/issues/427 reported for Sprotty, it seems that it's actually elkjs that's failing to delete the old bend points. The responsible class is [JsonImporter](https://github.com/eclipse/elk/blob/master/plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend).

Just looking at the code, my assumption is that this method in particular should delete old bend points from the JsonObject in case none are provided by the layout algorithm:
https://github.com/eclipse/elk/blob/c6f44e8a09d092fb69cb220dd1074f543bee35c0/plugins/org.eclipse.elk.graph.json/src/org/eclipse/elk/graph/json/JsonImporter.xtend#L562

Can anyone confirm this?

**Comment by Eddykasp** [comment]
I reproduced the issue:
Unlayouted graph: [graph-pre-layout.json](https://github.com/eclipse/elk/files/14373375/graph-pre-layout.json) produces: 
![graph-pre-layout](https://github.com/eclipse/elk/assets/10957098/f435a72a-9ec3-4f5a-9014-72965516a732)

If I then change the height of n1 to 70 as in this file
[graph-1-layout.json](https://github.com/eclipse/elk/files/14373390/graph-1-layout.json) and then run elk again I get the following drawing
![graph-1-layout](https://github.com/eclipse/elk/assets/10957098/fa70101a-c7f9-4829-8e4d-49dd9ff87a92)
and this output
[final-layout.json](https://github.com/eclipse/elk/files/14373443/final-layout.json).

On [elk-live](https://rtsys.informatik.uni-kiel.de/elklive/json.html?compressedContent=N4KABGCWAmBcYCIBOB7FAXBAacYA2AhgJ4oCu6A8gA7qQoB2AzvMGAOQF4DmKSk6ACwC2beG0JEApkknQ2YAL44IAYwGQ80GfXgBtXBFYx4CegEZsYAO4xB8AMwAGLGAGTIXAengB2R4uUIMCM4RHoAJksbaDswJxc3Dy8HfyUDYKhQ03so2wEUhPdPbzjU3ABdQNkuSWYwfSCM40RJCxdGMiQVWr0wizBKsHQCJBr0Ot0wyIGA9JCTSUj2zu6JvoQBl2HRyXHe7I3yxQqQBSA) this works correctly since each layout is fresh.
