### ISSUE TITLE
Improve documentation generation

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#131]
A collection of things we should improve: 
 * In the list of _all_ options, the options should state which layout algorithms support them. 
 * In the list of groups, the group's id should include all groups. For instance, `bk` makes more sense if it reads `nodePlacement.bk`.

**Comment by le-cds** [comment]
> In the list of groups, the group's id should include all groups. For instance, `bk` makes more sense if it reads `nodePlacement.bk`.

Done.

> In the list of all options, the options should state which layout algorithms support them.

This would mean that a change to ELK Layered's melk file could have consequences for options defined in the core melk file, requiring the documentation for the latter to be rebuilt. I'm not sure how (and if) this is possible (it probably is since changes to an xtend file have to cause dependent xtend files to be rebuilt, but I don't know how this works). @spoenemann Do you have any insights on this?

**Comment by le-cds** [comment]
I'm closing this without fixing the remaining part on the grounds of it not being worth the effort.
