### ISSUE TITLE
Advanced layout option values

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#14]
We had the idea to introduce a similar concept to the _advanced_ layout options for layout option values. This mainly makes sense for enum types. As an example consider different strategies for one of the layer-based approach's phases. `INTERACTIVE` layering would be an advanced option since additional knowledge is required to use it properly. 

In the layout view, advanced options should only be presented to the user if he selected the advanced mode. In the textual editor, content assist entries should be annotated accordingly. In the documentation advanced options should be separated from the regular options. 

A possible solution is to introduce an interface with methods `isExperimental()` and `isAdvanced()`. Enumerations _can_ implement the interface which is then evaluated by the layout view and the content assist provider.

**Comment by le-cds** [comment]
I added two annotations to annotate enumeration constants with: `AdvancedPropertyValue` and `ExperimentalPropertyValue`. The textual KGraph editor uses these to display hints in its code completion proposals. It seems that it is quite a bit harder to hide property values in cell editors of property sheets since the cell editors don't have knowledge of whether the property sheet is in advanced mode or not.

**Comment by le-cds** [comment]
This is an old one I wanted to have closed. I implemented changes to the layout property view that cause it to decorate advanced and experimental layout option values as being just that. Those decorations only appear when selecting an item for an enumeration option / selecting items for an enumeration set option. The view displays the current property values without the decorators. Changing that seems to be rather complicated and just not worth the effort.
