### ISSUE TITLE
NPE in LGraphUtil#createExternalPortDummy

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#160]
One of the arguments of the `LGraphUtil#createExternalPortDummy` method is `portPosition`. The port position is used whenever port constraints are at least fixed order. 

In `CompoundGraphPreprocessor#createExternalPortDummy` the method above is called with `null` for `portPosition`. As soon as a hierarchical node has fixed order ports, an NPE is thrown.

**Comment by philip-alldredge** [comment]
I believe this is the same issue I have encountered. 
Test case:

```
algorithm: layered
hierarchyHandling: INCLUDE_CHILDREN

node r {
	node n1 {
		layout [ size: 100, 100 ]

		node n3 {
			layout [ size: 100, 100 ]

			port p1 {
				layout [
					size: 10, 10  
					position: 50, 0
				]
				^port.side: NORTH	
			}
		}
	}
	
	node n2 {
		layout [ size: 100, 100 ]
		org.eclipse.elk.portConstraints: FIXED_POS // Disabling this line prevents the exception
		
		node n4 {
			layout [ size: 100, 100 ]
			//org.eclipse.elk.portConstraints: FIXED_POS
			
			port p1 {
				layout [  
					size: 10, 10 
					position: 50, 0
				]
				^port.side: NORTH	
			}
		}
	}

	edge n1.n3.p1 -> n2.n4.p1	
	edge n1.n3 -> n2.n4
}
```

**Comment by le-cds** [comment]
I did fix the NPE. However, the code probably won't work reliably with long hierarchical edges that move into (or out of) hierarchical nodes with port constraints set to `>= FIXED_ORDER`. This is because we cannot derive a proper position for where the edges should enter (or leave) a hierarchical node.

The safest way is to use hierarchical layout only with port constraints `<= FIXED_SIDE` or with only short hierarchical edges.
