### ISSUE TITLE
Transform NPE during layout with Sirius

### ISSUE THREAD

**Issue by kstaal** [eclipse/elk#280]
I tried to improve the layouting of Sirius by installing ELK.

When performing the layout (arrange-all) option of Sirius an error occurs. No layouting is done and an error message dialog is shown. Same result for release versions 0.3.0 and nightly build 0.4.0.20180101

Message:
Failed to perform diagram layout.
java.lang.NullPointerException

Stacktrace
java.lang.NullPointerException at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.transformExternalPort(ElkGraphImporter.java:603) at org.eclipse.elk.alg.layered.graph.transform.ElkGraphImporter.importGraph(ElkGraphImporter.java:94) at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:34) at org.eclipse.elk.alg.layered.graph.transform.ElkGraphTransformer.importGraph(ElkGraphTransformer.java:1)	at org.eclipse.elk.alg.layered.LayeredLayoutProvider.layout(LayeredLayoutProvider.java:53) org.eclipse.elk.core.RecursiveGraphLayoutEngine.layoutRecursively(RecursiveGraphLayoutEngine.java:183	
at org.eclipse.elk.core.RecursiveGraphLayoutEngine.layout(RecursiveGraphLayoutEngine.java:60)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:682)
	at org.eclipse.elk.core.service.DiagramLayoutEngine.layout(DiagramLayoutEngine.java:614)
	at org.eclipse.elk.core.service.DiagramLayoutEngine$1.execute(DiagramLayoutEngine.java:382)
	at org.eclipse.elk.core.service.util.MonitoredOperation$1.run(MonitoredOperation.java:236)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Work

**Comment by kstaal** [comment]
Using Eclipse Version: Oxygen.2 (4.7.2)

**Comment by le-cds** [comment]
The offending line is the second of the following two:

```java
dummy.setProperty(LayeredOptions.SPACING_LABEL_PORT,
        elkgraph.getParent().getProperty(LayeredOptions.SPACING_LABEL_PORT));
```

It seems that the root of the layout graph has an external port. This is not supported by ELK Layered. What it expects is a root node which represents the diagram itself. That root node may then contain nodes that have children themselves.

I believe this is an issue that needs to be fixed in the layout connector used for Sirius diagrams. ELK does not ship with one yet, but the Sirius developers are currently looking at building one.
