### ISSUE TITLE
Expressive error dialog in Eclipse's UI

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#329]
Currently, when an error occurs during layout within Eclipse, it is reported using a dialog that looks something like this: 
![exc](https://user-images.githubusercontent.com/7552459/39493912-cf4bb536-4d94-11e8-8862-deab0104b9b5.png)

The _details_ section just repeats the actual error, which is not really helpful. Instead, the stacktrace could be shown, which is available at this point (it's printed to the console log). 
I believe the way the dialog is composed is Eclipse-specific, not ELK (ELK just passes the `IStatus` object which includes the full exception.

**Comment by le-cds** [comment]
The details of how this works are buried deep within Eclipse (see the `org.eclipse.ui.internal.statushandlers.InternalDialog` class for details). As far as I can see, the details area only really makes sense if the status object is a multi status.

Since we can hardly influence this, I vote for closing the issue.

**Comment by uruuru** [comment]
Maybe we could provide a custom dialog? I'm tempted to agree with you ... but this dialog annoys us for years already.

**Comment by le-cds** [comment]
We discussed that since the original dialog already provides a link to the error log, we won't invest the work of implementing a custom dialog.
