### ISSUE TITLE
Question: Fixed Layout & Edge Routing

### ISSUE THREAD

**Issue by azriel46d** [eclipse/elk#355]
Hi, given that I already have **all** the node positions prior to getting a layout from ELK is it possible to 
either 
1. Use Fixed Layout and get the Edge Routes 
2. Use Layered Layout with fixed (locked) nodes (am seeing the Position attribute with Layered but haven't gotten it to work).

Thanks

**Comment by uruuru** [comment]
Hi, sadly the answer is no. There's an open feature request for standalone edge routing #315 and there've been various requests to add this functionality [1, 2] but it's not on the current agenda. 

Regarding your second point, yes there's the position layout option. But it cannot be used it _precisely_ fix the positions of the nodes during layered layout. You can use the various interactive strategies to _somewhat_ preseve the topology of the positions you already have. (It might be enough or may even be require to use a node's _regular position_ instead of the layout option though; I'm not completely sure right now):
* [Cycle Breaking Strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-cyclebreaking-strategy.html)
* [Layering Strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html)
* [Crossing Minimization Strategy](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingminimization-strategy.html) or [Semi Interactive](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-crossingminimization-semiinteractive.html) (with layer sweep)

[1] https://www.eclipse.org/forums/index.php/t/1086846/
[2] https://www.eclipse.org/forums/index.php/t/1093001/

**Comment by le-cds** [comment]
Just for completeness's sake: #315 tracks our desire to have a stand alone edge router.
