### ISSUE TITLE
[alg-layered] [question] HyperEdges not supported?

### ISSUE THREAD

**Issue by Nic30** [eclipse/elk#367]
Hello,

I am working on hardware circuit visualizer for document generator, [prototype](
https://hwtlib.readthedocs.io/en/latest/_static/schematic_viewer/schematic_viewer.html?schematic=../../_static/hwt_schematics/hwtLib.logic.crc.Crc.json).

I would like to use hyper edges for layered graphs (otherwise generated json is too big for even simple components).

I see that there is check for hyperedges in importer:
https://github.com/eclipse/elk/blob/fa89f2adf6d5b419954d851ab6056bf99c05c5eb/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphImporter.java#L1048

But is it necessary?
I can emulate hyperedges, but it seems to me that the code of layered layouter does supports it.
Does it?

**Comment by le-cds** [comment]
Short answer: It only supports emulating hyperedges through regular edges.

Long answer: When we brought the project over to the Eclipse Foundation, we took the opportunity to redesign our basic graph data structure. To be ready for future developments, we decided to have it support hyperedges right out of the box. Our algorithms, however, haven't yet been adapted accordingly since that's a whole lot of work. As it is, ELK Layered supports "simulated" hyperedges: when regular edges share a port, they are assumed to be part of a hyperedge.

**Comment by Nic30** [comment]
Ok,

I will keep the emulation of hyperedges together with 
```
org.eclipse.elk.layered.mergeEdges = 1
```

**Comment by saulshanabrook** [comment]
Are hyperedges not supported still in the layered algorithm?

In the [ELKT Editor](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) if I try:

```
algorithm: layered

node n1
node n2
node n3
edge n1, n2 -> n2
edge n1 -> n3
```

It errors with `IllegalArgumentException: Passed edge is not 'simple'.`

If I add the mergeEdges config I still seem to get the error

**Comment by uruuru** [comment]
> Are hyperedges not supported still in the layered algorithm?

Yes. Only in the ways described above.
