### ISSUE TITLE
Small port label position offsets between UP and DOWN layout

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#405]
There are small port label position offsets between the results generated for `DOWN` and `UP` layouts:

![screenshot 2019-02-20 at 14 12 05](https://user-images.githubusercontent.com/7465584/53094200-c78ef480-3519-11e9-8afd-f0dec5dd1f27.png)

Note how, in the picture, `P1` and `P2` have slightly different y coordinates.

**Comment by uruuru** [comment]
Also the labels are placed slightly differently, right?

**Comment by uruuru** [comment]
The port positions are equal by now (see the succeeding test in the referenced commit).

However, the label positions are still different:
```
ElkLabel "P1" (-14.0,-12.4990234375 | 13.0,11.4990234375)
ElkLabel "P2" (-14.0,-17.4990234375 | 13.0,11.4990234375)

ElkLabel "P2" (-14.0,6.0 | 13.0,11.4990234375)
ElkLabel "P1" (-14.0,1.0 | 13.0,11.4990234375)
```
In both cases they differ by `5`, which happens to be the default `nodeLabels.padding`. Changing that to `nodeLabels.padding: "[top=0.0,left=0.0,bottom=0.0,right=0.0]"` results in an equal label position. 
Thus, maybe there's an additional padding added accidentally.

**Comment by uruuru** [comment]
The issue seems to be that the `nodeLabels.padding` is not considered at all when mirroring in the `GraphTransformer`. 

Another question: @le-cds is there an expected order of the ports when no connections exist? I.e. if the textual order is p1, p2, would you be fine with the following result?
![image](https://user-images.githubusercontent.com/7552459/79358869-17acef80-7f42-11ea-850b-7836c9bf55ba.png)

The question is relevant when writing a test comparing the positions of the different ports for different directions.

**Comment by le-cds** [comment]
> Question: should the `nodeLabels.padding` influence the positioning of `OUTSIDE` port labels at all?

No, and I'm really puzzled if it does. This part of the code is supposed to setup the spacing between outside node labels and the node by adjusting the padding of the outer label cells accordingly:

https://github.com/eclipse/elk/blob/85bb5bdd9ab455184b31717eeb33d6555a1f93d7/plugins/org.eclipse.elk.alg.common/src/org/eclipse/elk/alg/common/nodespacing/internal/algorithm/NodeLabelCellCreator.java#L94-L129

No mention of the node label padding there. One thing I'm wondering is if the label sides here might be out of sync with the state of the layout graph as it is when this code is called.

> Another question: is there an expected order of the ports when no connections exist? I.e. if the textual order is p1, p2, would you be fine with the following result?
> ![image](https://user-images.githubusercontent.com/7552459/79358961-3ad79f00-7f42-11ea-87e0-6a8342ea09e7.png)

Following the _principle of least astonishment_, which I believe you quoted in your thesis, we should adhere to the order of ports in the input graph if sensible. The same is true, by the way, for the order of nodes, but that's a whole different issue. So yes, `P1` should ideally always be placed above `P2`.

Not sure how difficult that would be to implement, though.

**Comment by uruuru** [comment]
> No mention of the node label padding there. 

Lines 102 and 103? The padding is loaded into `nodeContext.nodeLabelsPadding`. 

> Not sure how difficult that would be to implement, though.

Hence, for the current code, the tests must not expect a particular order.

**Comment by le-cds** [comment]
> Lines 102 and 103? The padding is loaded into nodeContext.nodeLabelsPadding.

Yep, but only applied to the **inside** node label container. 

> Hence, for the current code, the tests must not expect a particular order.

Exactly. :)

**Comment by uruuru** [comment]
I investigated a bit further. It turns out altering the padding has no effect after all, I must've misconfigured something to falsely trigger that behavior. 

However, changing how the positions of port labels are mirrored in the `GraphTransformer` gives me satisfactory result. 
 * Considering the corresponding port's width when mirroring in x
 * _Not_ considering the label's height when mirroring in y


Before:

![image](https://user-images.githubusercontent.com/7552459/79878663-f76fab80-83ed-11ea-8896-3fc2d1db48be.png)

![image](https://user-images.githubusercontent.com/7552459/79878627-ec1c8000-83ed-11ea-8b2e-eec9ac424fe3.png)

![image](https://user-images.githubusercontent.com/7552459/79878548-d8711980-83ed-11ea-8505-3fd052397423.png)

After:
![image](https://user-images.githubusercontent.com/7552459/79877903-19b4f980-83ed-11ea-9c93-24021d8125d3.png)

![image](https://user-images.githubusercontent.com/7552459/79877934-20437100-83ed-11ea-9f79-8eb357a128b5.png)

![image](https://user-images.githubusercontent.com/7552459/79878498-c7280d00-83ed-11ea-935a-0b64a06fde88.png)


@le-cds is there any label placement configuration that must be checked as well? `portLabels.nextToPortIfPossible: true`, I presume, for instance.

Another note: in the "second example" it's somewhat unfortunate that for LEFT and RIGHT the port's label is once placed on the left and once on the right side of the port.

**Comment by le-cds** [comment]
> @le-cds is there any label placement configuration that must be checked as well? `portLabels.nextToPortIfPossible: true`, I presume, for instance.

I don't see why. The label placement algorithm places them relative to the port coordinates, and this code then transforms them back assuming they are placed relative to the port as well. Am I missing something here?

> Another note: in the "second example" it's somewhat unfortunate that for LEFT and RIGHT the `P2`'s label is once placed on the left and once on the right side of the port. The same holds for `P1` and UP and DOWN. I'd suggest to open a different ticket for this. Thoughts?

We could do so, but implementing a fix would probably mean making the label placement code way more complex. It currently assumes that labels can only be placed off to one side of a port. Fixing this would mean breaking with that assumption.

I'm not sure if it's worth the effort. Does anyone even use right-to-left layout? 😄
