### ISSUE TITLE
Polyline edge routed over node

### ISSUE THREAD

**Issue by shean42** [eclipse/elk#515]
In the attached graph there is a single unexpected edge and I'm wondering why it is routed over a node. 

![polyline](https://user-images.githubusercontent.com/22164312/75978542-07cfd380-5edf-11ea-99da-cb698902661e.png)

Not sure if this is a mis-configuration, an algorithm effect or just a situation that can't be helped?! Also the example resisted my attempts to minimize it, i.e. every time an element is removed the effect is not visible anymore (didn't try all combinations though :-)

Any insights?

[Polyline_edge_routed_over_node.json.zip](https://github.com/eclipse/elk/files/4292695/Polyline_edge_routed_over_node.json.zip)

**Comment by le-cds** [comment]
My first instinct is that this is a problem in how polyline edge routing handles north / south port dummies. I'll classify this as a bug for now and will look into it as soon as I find the time. 🙂

**Comment by le-cds** [comment]
Interestingly, I cannot reproduce the problem on the Java version:

<img width="1037" alt="Screenshot 2020-03-27 at 17 46 02" src="https://user-images.githubusercontent.com/7465584/77779575-095e6880-7053-11ea-8d00-b961d698dd2c.png">

@uruuru Do you have any idea what might cause the different results?

**Comment by uruuru** [comment]
Did you use the json input in Eclipse? Or do you have an elkt for it? 

I could imagine that the web viewer (elkgraph-web) somehow misses a bendpoint. 

Would be interesting to feed both an elkt and a json to the web viewer (as the elkt version uses java layout and the json version elkjs).

**Comment by le-cds** [comment]
> Would be interesting to feed both an elkt and a json to the web viewer (as the elkt version uses java layout and the json version elkjs).

Good point. So far, I had only tried the json version inside Eclipse. Transforming it into an elkt version gave the same results inside Eclipse (which was to be expected). But, as you hypothesised, feeding that to the elkt web viewer also spares us the node-edge overlap.

This should probably be either an elkjs or an elkgraph-web ticket, then?

**Comment by uruuru** [comment]
Could you post the elkt version here as well? I'll have a look at the web viewer then.

**Comment by le-cds** [comment]
Sure, here you go:

[515_edgeNodeOverlap.zip](https://github.com/eclipse/elk/files/4410103/515_edgeNodeOverlap.zip)

I cleaned it up only to the extent it required for the web viewer to not throw problem markers at me.

**Comment by uruuru** [comment]
While looking for a smaller example, I found this one: 
```
algorithm: layered
edgeRouting: POLYLINE

node n1 {
    layout [ size: 20, 100 ]
}
node n3 {
    portConstraints: FIXED_SIDE
    port p1 {
        ^port.side: NORTH
    }
}
node n4 {
    layout [ size: 20, 300 ]
}
edge n1 -> n3.p1
edge n1 -> n4
```

It produces an overlap even in the ELK version:
![image](https://user-images.githubusercontent.com/7552459/78062399-ee5f6180-738e-11ea-9eec-56975b5ed9ab.png)

I presume the core issue is a different one but should be investigated either way.

**Comment by le-cds** [comment]
@uruuru I don't think we have special treatment for north / south dummy ports when it comes to their x position. In this case, both the original node and the dummy would be placed at the layer's left boundary, since both have connections to the left only. Adapting their position to the position of their port makes sense, but doesn't always work since one dummy might represent connections to more than one north / south port. I see two options for fixing this:

1. Make the `PolylineEdgeRouter` aware of edges connected to north / south ports and use the x coordinate of those ports in the calculations you cited. This of course would require the edge router to be aware of north / south edges.
1. Make the `NorthSouthPortPostprocessor` aware of the problem and have it insert an additional bend point at a layer's left or right boundary if polyline edge routing is enabled. This would require the postprocessor to know about edge routing details.

None of the options seem ideal to me, but the first option might spare a few bend points from being introduced.

**Comment by uruuru** [comment]
For the record: I went for option 1). 

@shean42 fyi - it should be fixed in the java nightlies. elkjs won't include until its next release though.

**Comment by shean42** [comment]
Great, thanks for working on this!!
