### ISSUE TITLE
Add option to set layout option for all descendents

### ISSUE THREAD

**Issue by soerendomroes** [eclipse/elk#617]
When using interactive layout, it is necessary to set the `interactiveLayout` option for all nodes. That are somehow involved and at least for all nodes, which have children that have interactive constraints set.

For this use case and others I suggest to make this behavior configurable in the meta language.
This could be possible by setting a  `recursive` value for `targets` for a layout option.

**Comment by uruuru** [comment]
Some thoughts:
 * `recursive` is not really a `target` but a way _how_ to configure
 * you can probably use a `LayoutConfigurator` with `configure(ElkNode.class).setProperty(interactive, true)` to achieve your desired behavior. 
* The way you describe it, it wouldn't be possible to _stop_ interactive layout at some point, right?
* Maybe you could use your custom graph configurator to mimic this behavior?
* I feel it could be rather intricate to properly integrate the desired behavior - it also depends on the level at which you want to add the behavior. Should it be supported by the diagram layout engine, the recursive layout engine, only the layered layouter?

**Comment by soerendomroes** [comment]
> Maybe you could use your custom graph configurator to mimic this behavior?

I already set `interactive` with a custom graph configurator. The `interactiveLayout` option is set in the model file to allow to interactively set constraints to, for example, fix position of nodes in a layer for the layered approach. This option also enables that algorithm specific constraints are set in a layout run that is not `interactive`, i.e. the layout run before the `interactive` run to save the layer and position a node was originally in. These original positions and layers are not always necessary to get the desired result, if I find a good example I will post it here.

> I feel it could be rather intricate to properly integrate the desired behavior - it also depends on the level at which you want to add the behavior. Should it be supported by the diagram layout engine, the recursive layout engine, only the layered layouter?

It would be nice to have a workflow in which only `interactiveLayout` has to be added at the root node and children are aware of this.
Since interactive layout should not only work for layered, but for several more algorithms, it should be either in the diagram layout engine or the recursive layout engine.
If this feature is too complicated, I could always do this in before calling layout for this specific use case.
One could also always try to check the root node for the `interactiveLayout` property.
Maybe the latter would be the best option.

> recursive is not really a target but a way how to configure

Maybe I do not want to set it recursively but only allow to set it at a root node or as a global option.

> The way you describe it, it wouldn't be possible to stop interactive layout at some point, right?

One could recursively go through a graph and step other a branch that has the property set to a different value.

**Comment by uruuru** [comment]
Note that we already have a layout option that requires similar treatment: `LAYOUT_HIERARCHY`. It propagates automatically unless explicitly set to `SEPARATE_CHILDREN`. It requires special code both in the recursive graph layout enigne and the layered algorithm. 

Since adding special code for an individual layout option makes the code more complicated and error-prone, I'd like to verify first if the existing mechanisms could already be sufficient. 

If not, maybe it's an idea to somewhat _merge_ the new option and the `LAYOUT_HIERARCHY` option in that they share most of custom code and only in the last moment the decision is made whether hierarchical layout is activated or whether interactive layout is. 

There are two questions to be answered here, I guess:
1) do we want to support some generic mechanism that allows to explicitly propagate the value of a layout option to children. This is what the title of the ticket aims at. We hat this discussion before and as far as I remember we refrained from implementing it due to the fact that it makes things more complicated and due to the fact that it can easily be programmed by a user. @le-cds please correct me if I remember wrongly. 
1) can your use case of activating _interactive layout_ be realized with the current mechanisms? Is there maybe a more convenient way? Can 1) help with this. This question should, however, be answered separately. Maybe we could have an offline discussion?

**Comment by le-cds** [comment]
Late-to-the-party thoughts:

* I agree with @uruuru, inheritance has nothing to do with what kinds of graph elements a given property. If we want to add support for inherited layout options, it would have to be a separate property of an option.
* Regarding how to stop the inheritance, `LAYOUT_HIERARCHY` is an excellent example: explicitly setting the property on a graph element overrides the value which would otherwise be inherited. That's the way to go, and should we implement something like this, this is exactly how we should do it.
* I believe @uruuru is correct in that we chose not to do something like this because it can be done by users. However, things have changed since then. The `RecursiveGraphLayoutEngine` already runs a `LayoutAlgorithmResolver` on the whole graph before running layout, and we could easily add a configurator which takes care of property inheritance.
* Having said all that, I'm not sure how many people there really are who would use this feature...
