### ISSUE TITLE
Report invalid hierarchical cross min configuration instead of fixing it. 

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#651]
As we started reporting invalid configurations to users instead of failing silently or adjusting the configuration accordingly (to avoid confusion/unexpected behavior on the user side), I suggest to throw an `UnsupportedGraphConfigurationException` in the following case.

Alternatively we could adjust the layout option's documentation. 

Also, from a first look, I'd say line 388 should contain an `!=`, not a `==`.

https://github.com/eclipse/elk/blob/4bab504c10535ab39081dfbcfb4ad11f405bc6e4/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/ElkLayered.java#L330-L344

**Comment by le-cds** [comment]
Should we always fail here or only if the user explicitly set the property to something other than the layer sweep heuristic?

**Comment by uruuru** [comment]
Only if it's set to something else.

**Comment by soerendomroes** [comment]
Do not think line 388 is wrong.
Because of #228 we should not have an hierarchy aware processor in a child node if the root node is not the same processor. We have only one of these processors, which is the `LayerSweepCrossingMinimizer`. We check (if the root node does not have the only hierarchy aware processor set i.e. layer sweep set) whether any child node has layer sweep set and override it.
I suggest changing line 339 to `throw new UnsupportedGraphConfigurationException()` to report this problem.

We should also try to collect these kinds of inconsistencies somewhere to potentially fix them.

**Comment by soerendomroes** [comment]
I think I fixed this the wrong way.
