### ISSUE TITLE
Converting from ELKT to JSON loses graph structure

### ISSUE THREAD

**Issue by Baltoli** [eclipse/elk#699]
When converting between the two formats using the ELK Live converter [here](https://rtsys.informatik.uni-kiel.de/elklive/conversion.html), or my own code that calls `ElkGraphJson.toJson()`, the graph is rendered differently between the input ELKT and output JSON versions.

Concretely, many (but not all) subgraph boxes are no longer drawn, and label placement changes. The overall structure of the graph appears similar, but it is no longer laid out in a legible way.

The example ELK file I'm looking at is [here](https://gist.github.com/Baltoli/22b698f49f65453b1e123c4ceda933d0).

Steps to reproduce:
1. Render the input graph from my Gist in the [viewer](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html) to see the correct structure and layout of subgraphs & labels.
2. Convert the ELK file to JSON using the [converter](https://rtsys.informatik.uni-kiel.de/elklive/conversion.html).
3. Render the converted JSON using the alternative [viewer](https://rtsys.informatik.uni-kiel.de/elklive/json.html). Note that the graph appears structurally similar, but is no longer readable due to labels intersecting and missing subgraph boundaries.

Is this a known issue, and if so is there a way to convert to JSON while preserving these elements of the layout? Any solution is welcome, including changing the structure of the ELK code we generate.

The other possibility is of course that the ELK-Live rendering code is broken for JSON inputs. If this is the case, I'd appreciate pointers on what options it's breaking to render the graph as it's doing.

Thanks for your help!

cc: @javierariasmoreno

**Comment by uruuru** [comment]
Thanks for your detailed feedback. 

I could imagine that it's due to the fact that the elkt viewer and json viewer work slightly differently. 

For your node sizes to be properly computed you require that the nodes' labels get assigned proper dimensions (you use `nodeSize.constraints: "NODE_LABELS"` and do not specify any node and label dimensions). 

While the elkt viewer seems to infer the labels' dimensions, for the json viewer this is simply not the case, I believe. 

@spoenemann the label dimension computation should happen in sprotty on client side, right? Do you see an easy way to add the behavior to the json viewer as well? The difficulty could be that at the moment the json is fed directly to the layouter and only _after_ the layout has been computed, the SGraph for rendering is constructed. 

If I'm correct, the issue is more about elk-live's json viewer. From a first glance there's nothing lost during the conversion (since no dimensions ever existed that could be lost).

**Comment by Baltoli** [comment]
That's very helpful, thank you! Just to check I understand, if we were to work out a label size manually in our ELK generator, the problem would be resolved?

I do see that using `PORTS` rather than just `NODE_LABELS` seems to improve things even without assigning a size.

**Comment by uruuru** [comment]
> That's very helpful, thank you! Just to check I understand, if we were to work out a label size manually in our ELK generator, the problem would be resolved?

Yes, I'd assume so. 

> I do see that using PORTS rather than just NODE_LABELS seems to improve things even without assigning a size.

I could imagine that some default minimum size is applied as soon as `PORTS` is added. As soon as the labels get larger they'll probably reach out of the node's boundary though.
