### ISSUE TITLE
New graph structure

### ISSUE THREAD

**Issue by le-cds** [eclipse/elk#74]
ELK's current graph data structure was developed years ago and is a bit awkward to use. Introduce a new graph data structure, the `ElkGraph`, that primarily focuses on the following issues:
1. Get rid of `KShapeLayout` and `KEdgeLayout`. Layout information should become a first-class citizen.
2. Introduce a way to model hyperedges. Currently, edges can only connect one source to one target.

**Comment by le-cds** [comment]
A first proposal for the new graph structure can be found in the `cds/elkgraph` branch, in a temporary package called `org.eclipse.elk.graph.graph` (this will change once we start to adapt the new branch). Feel free to comment on the design and implementation and leave comments in this ticket. The most important things to look at:

1. The new structure itself (basically everything directly contained in the `org.eclipse.elk.graph.graph` package).
1. The accompanying utility class, `org.eclipse.elk.graph.util.ElkGraphUtil`. The class contains a few implemented methods as well as a few stubs.

**Comment by uruuru** [comment]
Some comments from my side:

* What about the old `KInsets`? If we move layout information to the model itself, should they be included as well? On the other hand, they may be superfluous if we require the layout engine to apply them. 
* Why `childNodes` instead of `children`?
* Maybe just `set` instead of `setLocation` for bend points. 
* I like having `hierarchical` and `hyperedge` as transient flags.
* Would it help if the `ElkEdgeSection` knew whether it represents a polyline or the control points of a spline?
* I think it would be a good idea to check the [GraphML Primer](http://graphml.graphdrawing.org/primer/graphml-primer.html). Maybe they addresses something we forgot about so far. There's also a recent [book chapter](https://cs.brown.edu/~rt/gdhandbook/chapters/graphml.pdf) on GraphML.

Regarding the utility class:
* `createHyperedge(Iterable, Iterable)` instead of collection?
* `public updateContainment(edge)` should this be called by the user, _ever_? Make it private otherwise. 
* `// TODO: Should the return type really be an edge, or an iterable?` I guess you mean `List`: iterable is not necessarily ordered and does not allow to get the size fast. If it's implemented using a concatenating iterable, it would be extra effort to create a list for it ... Algorithms may call it quite frequently, so I would make it fast.

**Comment by le-cds** [comment]
Some thoughts from my side... ;)

> What about the old KInsets? If we move layout information to the model itself, should they be included as well? On the other hand, they may be superfluous if we require the layout engine to apply them.

So, this is a bit of a tough decision. The two primary guidelines for designing the new graph structure were ease of use as well as the combination of structure and layout information. The problem is that the latter could actually prompt us to include all sorts of layout information into the graph, which is probably not what we should do. Instead, we should only include the bare minimum necessary to describe where things should be placed. This would argue against including insets. As a consequence, any layout information that depend on insets would thus have to be changed to not depend on them anymore. We should thus change the point nodes are placed relative to. In the old graph structure, they were placed relative to the top left corner of their parent node, plus the top and left insets. In the new graph structure, they should simply be placed relative to the top left point of their parent node. Which is easier to explain anyway.

> Why `childNodes` instead of `children`?

Different elements of the graph have different kinds of children. I wanted to make it obvious through the method name what type of children it would return. That is also why I have chosen `parentNode` over `parent`. Just seems to me to make the code a bit more self-descriptive.

> Maybe just `set` instead of `setLocation` for bend points.

Seems sensible.

> Would it help if the `ElkEdgeSection` knew whether it represents a polyline or the control points of a spline?

I'm not sure if that would really make a difference to the section. It's not like it could impose any restrictions on the number of bend points if it were a spline.

> I think it would be a good idea to check the GraphML Primer. Maybe they addresses something we forgot about so far. There's also a recent book chapter on GraphML.

That's a good idea, I'll do that. Thanks.

> `createHyperedge(Iterable, Iterable)` instead of collection?

Done.

> `public updateContainment(edge)` should this be called by the user, ever? Make it private otherwise.

Yes, it is supposed to once the user updates the end points of an edge. Granted, this is more of a graph-change scenario as oppsed to a graph-creation scenario and may thus be less common.

> `// TODO: Should the return type really be an edge, or an iterable?` I guess you mean `List`: iterable is not necessarily ordered and does not allow to get the size fast. If it's implemented using a concatenating iterable, it would be extra effort to create a list for it ... Algorithms may call it quite frequently, so I would make it fast.

Both decisions seem to have their downsides, so let's think about what the most common case is. I think it will be to iterate over incoming or outgoing edges, which would favour the Iterable return type.

**Comment by uruuru** [comment]
> Different elements of the graph have different kinds of children. I wanted to make it obvious through the method name what type of children it would return. That is also why I have chosen parentNode over parent. Just seems to me to make the code a bit more self-descriptive.
Shouldn't the variable name be descriptive enough, so that it reads `node.children()`?

> I'm not sure if that would really make a difference to the section. It's not like it could impose any restrictions on the number of bend points if it were a spline.
I thought of it as a hint to the rendering framework, not for validation. It would (possibly) allow to have a mixture of spline/polyline rendering for cross-hierarchy edges.

**Comment by le-cds** [comment]
> Shouldn't the variable name be descriptive enough, so that it reads `node.children()`?

It would be `node.getChildren()`, but yes, we could do that.

> I thought of it as a hint to the rendering framework, not for validation. It would (possibly) allow to have a mixture of spline/polyline rendering for cross-hierarchy edges.

That could always be done through layout options.

**Comment by uruuru** [comment]
>That could always be done through layout options.

An `ElkEdgeSection` (currently) does not implement `IPropertyHolder`. It would be important that the section, as opposed to the edge, knows about the polyline/spline difference.

**Comment by le-cds** [comment]
> An `ElkEdgeSection` (currently) does not implement `IPropertyHolder`.

Oops, you're right. I guess that's a reason for edge sections to derive from `EMapPropertyHolder`. Thanks for raising that point.

**Comment by le-cds** [comment]
> I think it would be a good idea to check the GraphML Primer. Maybe they addresses something we forgot about so far. There's also a recent book chapter on GraphML.

I finished reading up on GraphML. It seems that the features that can be expressed through GraphML are pretty much a subset of the features we can express with our new graph data structure, except for one detail. In GraphML, ports can have child ports. So far, we have not considered that this could be the case. I don't think I've ever seen a case where I would have used it. If the need for this arises, I think we could always add support for that later, but for now I would leave it out of our data structure for simplicity.

**Comment by spoenemann** [comment]
>> What about the old KInsets? If we move layout information to the model itself, should they be included as well? On the other hand, they may be superfluous if we require the layout engine to apply them.

> So, this is a bit of a tough decision. The two primary guidelines for designing the new graph structure were ease of use as well as the combination of structure and layout information. The problem is that the latter could actually prompt us to include all sorts of layout information into the graph, which is probably not what we should do. Instead, we should only include the bare minimum necessary to describe where things should be placed. This would argue against including insets. As a consequence, any layout information that depend on insets would thus have to be changed to not depend on them anymore. We should thus change the point nodes are placed relative to. In the old graph structure, they were placed relative to the top left corner of their parent node, plus the top and left insets. In the new graph structure, they should simply be placed relative to the top left point of their parent node. Which is easier to explain anyway.

👍  for simplicity. Insets have to be provided by the rendering framework and to be considered by the layout algorithm, but they're not required to describe the graph structure and layout. So move them to a layout option.

> > Shouldn't the variable name be descriptive enough, so that it reads node.children()?

> It would be node.getChildren(), but yes, we could do that.

But then also `parentNode` should be just `parent`.

> // TODO: Should the return type really be an edge, or an iterable? I guess you mean List: iterable is not necessarily ordered and does not allow to get the size fast. If it's implemented using a concatenating iterable, it would be extra effort to create a list for it ... Algorithms may call it quite frequently, so I would make it fast.
Both decisions seem to have their downsides, so let's think about what the most common case is. I think it will be to iterate over incoming or outgoing edges, which would favour the Iterable return type.

If you want a list, you can use `Lists.newArrayList(Iterable)` from Guava, so an Iterable should be good as default.

More things I found:

* Instead of creating an EMap in EMapPropertyHolder.properties, we could directly implement the IPropertyHolder methods by copying the implementation of MapPropertyHolder. That would allow to eliminate the ugly ElkPropertyToValueMapEntry. I think the EMap based solution is required only if you want to serialize the map, but in our case it's transient.

* The only remaining use case for ElkGraphData is KLighD's KRendering, right? Shouldn't we remove it completely from this metamodel? KLighD could define its own specialized graph elements that extend those from the ElkGraph and add a containment reference for the rendering. It shouldn't be a problem since we need transformations between the KLighD view model and the layout graph, anyway.

* Change `ElkPort.parentNode` to `containingNode` so it's consistent with the edges.

* ElkEdgeSection: `outgoingShape` &rarr; `targetShape` and `incomingShape` &rarr; `sourceShape`?

* It would be convenient to have utility methods that work on KVector and KVectorChain in ElkGraphUtil, but that would require to move those classes to elk.graph.

* I suppose in Elk Layered we still want to support the case where hyperedges are modeled through sets of simple edges because not all rendering frameworks support hyperedges (e.g. KLighD doesn't). That means we need a conversion between ElkGraph hyperedges and LGraph simple edges and between ElkGraph simple edges and LGraph simple edges (including hyperedge detection as done currently). That means we still need the `junctionPoints` option, and maybe even the `hypernode` option. This is a bit odd, but at least we have paved the way for better means of transporting hyperedge structure information.

**Comment by le-cds** [comment]
> :+1: for simplicity. Insets have to be provided by the rendering framework and to be considered by the layout algorithm, but they're not required to describe the graph structure and layout. So move them to a layout option.

Right, no insets then.

> But then also parentNode should be just parent.

I changed all such references to just `parent`. I also changed `edgeSections` simply to `sections` in `ElkEdge`.

> Instead of creating an EMap in EMapPropertyHolder.properties, we could directly implement the IPropertyHolder methods by copying the implementation of MapPropertyHolder. That would allow to eliminate the ugly ElkPropertyToValueMapEntry. I think the EMap based solution is required only if you want to serialize the map, but in our case it's transient.

I'm not sure yet if it will actually be transient or not. As noted in #75, it may actually be possible to get away without separate persistent entries, in which case the `EMap`-based solution would be the way to go. I'll leave that unchanged for now until we figure out what happens with #75.

> The only remaining use case for ElkGraphData is KLighD's KRendering, right? Shouldn't we remove it completely from this metamodel? KLighD could define its own specialized graph elements that extend those from the ElkGraph and add a containment reference for the rendering. It shouldn't be a problem since we need transformations between the KLighD view model and the layout graph, anyway.

Regarding KLighD, it is unlikely that we will be extending the ELK Graph for KLighD's new data structure. We are most likely to adapt the old KGraph a little. To keep the ELK Graph flexible, I would actually like to retain `ElkGraphData`.

> Change ElkPort.parentNode to containingNode so it's consistent with the edges.

I changed it to `parent` to be consistent with almost everything else. In fact, edges are a bit of a special case. The references are named `containedEdges` and `containingNode` to signify that this is not exactly a parent-child relationship as is the case with, for example, nodes and ports. The parent of a port is always the node it directly belongs to. With edges, the graph model itself is pretty free as to which node contains the edge. The node will usually not have much to do with the edge.

> ElkEdgeSection: outgoingShape → targetShape and incomingShape → sourceShape?

I would like to avoid confusion with the sources and targets of the edge.

> It would be convenient to have utility methods that work on KVector and KVectorChain in ElkGraphUtil, but that would require to move those classes to elk.graph.

Which, in my opinion, wouldn't be a problem. In fact, we could think about moving the whole `core.math` package over to the `elk.graph` plug-in.

> I suppose in Elk Layered we still want to support the case where hyperedges are modeled through sets of simple edges because not all rendering frameworks support hyperedges (e.g. KLighD doesn't). That means we need a conversion between ElkGraph hyperedges and LGraph simple edges and between ElkGraph simple edges and LGraph simple edges (including hyperedge detection as done currently). That means we still need the junctionPoints option, and maybe even the hypernode option. This is a bit odd, but at least we have paved the way for better means of transporting hyperedge structure information.

The current plan was to add methods to `ElkGraphUtil` that convert hyperedges to sets of simple edges and vice versa, being careful to not lose routing information in the process. A long-term goal could be to have ELK Layered support hyperedges out of the box, but until then I would propose to have it only support simple edges (which will work fine with the new graph format). If someone wants to have hyperedges, they will have to call the utility methods to convert those to sets of simple edges.

**Comment by spoenemann** [comment]
> Regarding KLighD, it is unlikely that we will be extending the ELK Graph for KLighD's new data structure. We are most likely to adapt the old KGraph a little. To keep the ELK Graph flexible, I would actually like to retain `ElkGraphData`.

Isn't the property mechanism flexible enough?

> Which, in my opinion, wouldn't be a problem. In fact, we could think about moving the whole `core.math` package over to the `elk.graph` plug-in.

👍

**Comment by le-cds** [comment]
> Isn't the property mechanism flexible enough?

It probably would be, but don't the two serve different purposes? Properties are meant for layout configuration, graph data were meant to allow clients to decorate the graph structure with application-specific data not relevant to layout.

**Comment by spoenemann** [comment]
The original idea behind graph data was something like *"maybe the KGraph could be used as a general graph data structure that will serve many different purposes in KIELER, so we need to make it easily extensible"*. My current understanding of the ElkGraph is *"the interface between layout algorithms and rendering applications"*. This more focused understanding does not need an extension mechanism for stuff that will never be used by the layout algorithms.

**Comment by le-cds** [comment]
That's pretty much the same argument I used against insets. You convinced me. ;)
