### ISSUE TITLE
LayerID for Nodes

### ISSUE THREAD

**Issue by mdbaehre** [eclipse/elk#780]
Is there a way to get the layerId calculated by the ELK for each node?  The reference documentation (https://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-layerId.html) describes an option - but no details on how to use it.

**Comment by uruuru** [comment]
At least for the layered algorithm it seems to be set: 
https://github.com/eclipse/elk/blob/3630e23fa5abc253233296e2bdf5e18828e5dba7/plugins/org.eclipse.elk.alg.layered/src/org/eclipse/elk/alg/layered/graph/transform/ElkGraphLayoutTransferrer.java#L161

Not sure if there's another step afterwards that may drop it again, though.

**Comment by mdbaehre** [comment]
The documentation says it is an "output" - so I was interpreting it to mean that setting it's value to a positive number would cause ELK to include the LayerId in the updated graph data in the same way that it adds the x and y values after calculating the layout.

**Comment by uruuru** [comment]
Yes, I agree.

**Comment by soerendomroes** [comment]
The `LAYERING_LAYER_ID` is part of the interactive `LAYER_COICE_CONSTRAINT` and `POSITION_CHOICE_CONSTRAINT`. It is preserved between consecutive layout runs, e.g. setting `interactiveLayout` to `true` adds a second layout run after the first that uses interactive strategies for cycle breaking, crossing minimization, etc. However, declaring it as an output property is still wrong since these values should not be written into the model file. It might depend on something concerning the `interactiveLayout` property and have a look into it for the next release.

**Comment by soerendomroes** [comment]
I looked it up and it is indeed only set by the corresponding processor if `interactiveLayout` is set.

**Comment by soerendomroes** [comment]
I want to give a should example how this works:
```
generatePositionAndLayerIds: true
node n1 // position 0, layer 0

node n2 // position 0, layer 0
edge n2 -> n3
node n3 // position 0, layer 1
```

If we handle the graph as one component this changes:
```
generatePositionAndLayerIds: true
separateConnectedComponents: false
node n1 // position 0, layer 0

node n2 // position 1, layer 0
edge n2 -> n3
node n3 // position 0, layer 1
```
