### ISSUE TITLE
Interactive crossing minimization yields nullpointer

### ISSUE THREAD

**Issue by uruuru** [eclipse/elk#80]
Laying out the graph below with `org.eclipse.elk.layered.crossingMinimization.strategy=INTERACTIVE` results in an NPE. 

The issue seems to be that the `LONG_EDGE_TARGET` of a long edge dummy isn't set; `targetPoint` is `null`.

```
LPort target = node.getProperty(InternalProperties.LONG_EDGE_TARGET);
KVector targetPoint = target.getAbsoluteAnchor();
```

```
properties: 
    org.eclipse.elk.layered.crossingMinimization.strategy=INTERACTIVE
knode {
    pos: x = 12 y = 14
    size: width = 10 height = 10
    klabel "node-1" 
    kedge (-> N1) {
        klabel "link-1"
    }
}
knode N1 {
    pos: x = 50 y = 15.666667
    size: width = 10 height = 10
    klabel "node-2"
    kedge (-> N2) {
        klabel "link-2" 
    }
}
knode N2 {
    pos: x = 84 y = 17.333334
    size: width = 10 height = 10
    klabel "node-3" 
}
knode {
    size: width = 10 height = 10
    klabel "node-4"
    kedge (-> N2) {
        klabel "link-3" 
    }
    kedge (-> N1) {
        klabel "link-4"
    }
}
```

**Comment by le-cds** [comment]
This is fixed now, together with an `ArrayIndexOutOfBoundsException` that occurred because the layer IDs were not properly initialized for the port distribution code. However, the results are probably not correct for your example graph because of the fact that the original long edge target cannot be retrieved when label dummy nodes are involved. This is tied to #96. Once we find a good solution there that does not involve resetting long edge source / target information, this should start working again. I'm therefore closing this ticket.
