### ISSUE TITLE
Radial layout with four children has a spacing issue

### ISSUE THREAD

**Issue by Eddykasp** [eclipse/elk#862]
When using radial layout on trees with four children, the default spacing seems to be too close causing artifacts in the edge routing.

[elk-live example](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE5o4AewSADiDgIxoDeRaXaoksiqNFGAEYoTtzIU0JZhK5TKJAEzyZ5JQGY1imQBYdGmQFY1hMEtYBaAHwzV3KgQszrdktsfnLaW-rRmzj5+JKYAvkSRujR0jDjK7Gq80PDI6MKi4o66cHLZRnAOkgWexdJwBl5BaLm+doWBLrV+cKVc3jVuNXoBEURAA)

**Comment by soerendomroes** [comment]
I don't think that we have to fix this, since the spacing can be set to a higher value and node size can be reduced, as seen [here](https://rtsys.informatik.uni-kiel.de/elklive/elkgraph.html?compressedContent=IYGw5g9gTglgLgCwLYC4AEJgE8CmUcAmAUAHYQE5o4AewSADiDgIxoDeRaXaoksiqNFGAEYoTtzIU0JVh24KM2CAFc4AbQDOMAF450zAAwAaNEYC6ErgF8rM8pRIAmO1McBmVw5kAWL9JIAVjtCMEdWAFoAPhkXBVDwtGiZT3iCMJlImJIfNBD0xOSgolsiUm8aOkYcJ3Y7TXpgAGMYEjAAOjcAOQcDQ0N2wzteaHhkdGFRcQU3NDhmf0o4OMlvOFTV6Tg-GbXgtIz5pJjl-MOsuY2uBLmL7byDpbvg0qA).
